services:
  redis:
    image: redis:7.4-alpine
    container_name: wad-redis
    restart: unless-stopped
    env_file:
      - .env
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis_data:/data
    networks:
      - wad

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    # environment:
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wad

  backend:
    build:
      context: ./backend
      network: host
    container_name: wad-backend
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ${HOST_MODELS_DIR}:/ai-models
    networks:
      - wad

  frontend:
    build:
      context: ./frontend
    container_name: wad-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - wad
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_www:/var/www/certbot

networks:
  wad:
    

volumes:
  postgres_data:
  redis_data:
  certbot_etc:
  certbot_www: