[pytest]
# Путь к тестам
testpaths = tests
# Добавляем текущую директорию в PYTHONPATH, чтобы импорты 'from app...' работали
pythonpath = .
# auto заставляет pytest-asyncio автоматически обрабатывать все async def фикстуры
asyncio_mode = auto
# Указываем область видимости цикла событий (требование новых версий)
asyncio_default_test_loop_scope = function